from fai.contracts import Read
from fai.logic import map_valid_delta_positions_for_read


def test_map_valid_delta_positions_for_read():
    gene_dict = {
        "gene1": "TAACAAACAAAACAAATACAATGGTCAAATTAACTTCAATCGCCGCTGGTGTCGCTGCCATCGCTGCTACTGCTTCTGCAACCACCACTCTAGCTCAATCTGACGAAAGAGTCAACTTGGTGGAATTGGGTGTCTACGTCTCTGATATCAGAGCTCACTTAGCCCAATACTACATGTTCCAAGCCGCCCACCCAACTGAAACCTACCCAGTCGAAGTTGCTGAAGCCGTTTTCAACTACGGTGACTTCACCACCATGTTGACCGGTATTGCTCCAGACCAAGTGACCAGAATGATCACCGGTGTTCCATGGTACTCCAGCAGATTAAAGCCAGCCATCTCCAGTGCTCTATCCAAGGACGGTATCTACACTATCGCAAACTAGAGACAAACGCCAATTTTACG",  # noqa: E501
        "gene2": "CATGAGGTCCCACTGTATGTATGTGCCCTCGCACAGTTTTGCTCATCATAAACATTAATCATTGGTTTTATGATAAGAATATCGTAAGAATTATTTTAACTTTCAGATTAGATTCCGGCCATATTTCTGACATTTGTTTTATTAATAAAAATTTGGCGAATGCTTTGATAACTGCTGATATTTCATTGTTGAAAAGGCATGATATAAGATGCACAAAGTATATTATAACTTATTATCAGAGATATAGGAACAAAGAAAAAGGGAAATTCATATCTCTATGTAAAAATACCATTATTTCCTCTTCTGTTTAATATGCTGTCCTTAATTTTCA",  # noqa: E501
        "gene3": "GTACAATAAAAGCCCCAAAAATGTCTCTGGCACATTATTGTTTACTACTAGCCATCGTCACATTGCTGGGATTAACTAATGTTGTCTCTGCGACTACAGCGGCATGCCTGCCAGCAAACTCAAGGAAGAATGGTATGAATGTAAACTTTTACCAGTATTCATTGAGAGATTCCTCCACATATTCGAATGCAGCATATATGGCTTATGGATATGCCTCAAAAACTAAACTGGGTTCTGTCGGAGGACAAACTGATATCTCGATTGATTATAATATTCCTTGTGTTAGTTCATCAGGCACATTTCCTTGTCCTCAAGAAGATTTATATGGTAATTGGGGATGCAAAGGAATTGGTGCTTGTTCTAATAATCCAATAATTGCATACTGGAGTACTGATTTATTTGGTTTCTATACTACCCCAACAAACGTAACCCTAGAAATGACAGGTTATTTTTTACCACCACAGACGGGTTCTTACACATTCAAGTTTGCTACAGTTGACGACTCTGCAATTCTATCAGTCGGTGGTAGCATTGCGTTCGAATGTTGTGCACAAGAACAACCTCCCATCACGTCGACTAACTTCACCATCAATGGTATCAAGCCATGGAATGGAAGTCCCCCTGATAATATTACAGGGACTGTCTACATGTATGCTGGTTTCTATTATCCAATGAAGATTGTTTACTCAAATGCCGTTGCCTGGGGTACACTTCCAATTAGTGTGACACTACCAGATGGCACTACCGTTAGTGATGACTTTGAAGGGTACGTATATACTTTTGACAACAATCTAAGCCAGCCAAACTGTACCATTCCAGACCCTTCAAATTATACTGTCAGTACTACCATAACTACAACGGAACCATGGACCGGTACTTTCACTTCTACATCTACTGAAATGACCACCGTCACCGGTACCAACGGCGTTCCAACTGACGAAACCGTCATTGTCATCAGAACTCCAACAACTGCTAGCACCATCATAACTACAACTGAGCCATGGAACAGCACTTTTACCTCTACTTCTACCGAATTGACCACAGTCACTGGCACCAATGGTGTACGAACTGACGAAACCATCATTGTAATCAGAACACCAACAACAGCCACTACTGCCATAACTACAACTGAGCCATGGAACAGCACTTTTACCTCTACTTCTACCGAATTGACCACAGTCACCGGTACCAATGGTTTGCCAACTGATGAGACCATCATTGTCATCAGAACACCAACAACAGCCACTACTGCCATGACTACAACTCAGCCATGGAACGACACTTTTACCTCTACTTCTACCGAATTGACCACAGTCACCGGTACCAATGGTTTGCCAACTGATGAGACCATCATTGTCATCAGAACACCAACAACAGCCACTACTGCCATGACTACAACTCAGCCATGGAACGACACTTTTACCTCTACTTCTACCGAATTGACCACAGTCACCGGTACCAATGGTTTGCCAACTGATGAGACCATCATTGTCATCAGAACACCAACAACAGCCACTACTGCCATGACTACAACTCAGCCATGGAACGACACTTTTACCTCTACATCCACTGAAATCACCACCGTCACCGGTACCAATGGTTTGCCAACTGATGAGACCATCATTGTCATCAGAACACCAACAACAGCCACTACTGCCATGACTACAACTCAGCCATGGAACGACACTTTTACCTCTACATCCACTGAAATGACCACCGTCACCGGTACCAACGGTTTGCCAACTGATGAAACCATCATTGTCATCAGAACACCAACAACAGCCACTACTGCCATAACTACAACTGAGCCATGGAACAGCACTTTTACCTCTACATCCACTGAAATGACCACCGTCACCGGTACCAACGGTTTGCCAACTGATGAAACCATCATTGTCATCAGAACACCAACAACAGCCACTACTGCCATAACTACAACTCAGCCATGGAACGACACTTTTACCTCTACATCCACTGAAATGACCACCGTCACCGGTACCAACGGTTTGCCAACTGATGAAACCATCATTGTCATCAGAACACCAACAACAGCCACTACTGCCATGACTACAACTCAGCCATGGAACGACACTTTTACCTCTACATCCACTGAAATCACCACCGTCACCGGTACCAACGGTTTGCCAACTGATGAGACCATCATTGTCATCAGAACACCAACAACAGCCACTACTGCCATGACTACAACTCAGCCATGGAACGACACTTTTACCTCTACATCCACTGAAATGACCACCGTCACCGGTACCAACGGCGTTCCAACTGACGAAACCGTCATTGTCATCAGAACTCCAACTAGTGAAGGTCTAATCAGCACCACCACTGAACCATGGACTGGTACTTTCACCTCTACATCCACTGAGATGACCACCGTCACCGGTACTAACGGTCAACCAACTGACGAAACCGTGATTGTTATCAGAACTCCAACCAGTGAAGGTTTGGTTACAACTACAACCGAGCCATGGACCGGTACTTTCACCTCTACATCTACTGAGATGACCACCATCACTGGAACCAACGGTCAACCAACTGATGAAACTGTCATTATTGTCAAAACTCCAACTACTGCCATCTCATCCAGTTTGTCATCTTCTTCAGGACAAATCACCAGCTTTATCACGTCTGCGCGTCCAATTATTACCCCATTCTATCCTAGCAATGGAACTTCTGTGATTTCCTCCTCAGTAATTTCTTCCTCAGACACTTCTTCTCTAGTCATTTCTTCCTCAGTCACTTCTTCTCTAGTCACTTCTTCTCCAGTCATTTCTTCTTCATTCATTTCTTCCCCTGTCATTTCTTCTACAACAACCTCCGCTTCTATACTCTCTGAATCATCTAAATCATCCGTCATTCCAACCAGTAGTTCCACCTCTGGTTCTTCTGAGAGCGAAACGGGTTCAGCTAGTTCTGCCTCTTCTTCCTCTTCTATCTCTTCTGAATCACCAAAGTCTACATATTCGTCTTCATCATTACCACCTGTTACCAGTGCAACAACAAGTCAGGAAATTACTTCTTCATTACCACCTGTTACCACTACAAAAACGAGCGAACAAACCACTTTGGTTACCGTGACATCCTGCGAATCTCATGTGTGCACTGAATCTATCTCCTCTGCGATTGTTTCCACGGCCACCGTTACTGTTAGCGGTGCCACAACAGAGTATACCACATGGTGCCCTATTTCTACCACAGAGATAACAAAGCAAACTACGGAGACAACAAAGCAAACCAAGGGGACAACAGAGCAAACCACAGAAACAACAAAACAAACCACAGTAGTTACAATTTCTTCTTGTGAATCTGACGTATGCTCTAAGACTGCTTCTCCAGCCATTGTATCTACAAGCACTGCTACTATTAATGGCGTTACCACAGAATACACAACATGGTGTCCTATTTCCACCACAGAATCGAAGCAACAAACTACGCTAGTTACTGTTACTTCCTGCGGATCTGGTGTGTGTTCCGAAACTACTTCACCTGCCATTGTTTCGACGGCCACGGCTACTGTGAATGATGTTGTTACGGTCTATTCTACATGGAGGCCACAGACTACGAATGAACAGTCTGTCAGCTCTAAAATGAACAGTGCTACCAGTGAGACAACAACCAATACTGGAGCTGCTGAGACAACTACCAGTACTGGAGCTGCTGAGACGAAAACAGTAGTCACCTCTTCAATTTCAAGATTCAATCATGCTGAAACACAGACGGCTTCCGCGACCGATGTGATTGGTCACAGCAGTAGTGTTGTTTCTGTATCCGAAACTGGCAACACCAAGAGTCTAACAAGTTCCGGGTTGAGTACTATGTCGCAACAGCCTCGTAGCACACCAGCAAGTAGCATGGTAGGATCTAGTACAGCTTCTTTAGAAATTTCAACGTATGCTGGCAGTGCCAACAGCTTACTGGCCGGTAGTGGTTTAAGTGTCTTCATTGCGTCCTTATTGCTGGCAATTATTTAATAAAATTCGCGTTCTTTTTA",  # noqa: E501
    }

    read = Read("gene1", 5, 30)

    expected_output = [
        False,  # Position 0
        False,  # Position 1
        False,  # Position 2
        False,  # Position 3
        False,  # Position 4
        False,  # Position 5
        False,  # Position 6
        False,  # Position 7
        False,  # Position 8
        False,  # Position 9
        False,  # Position 10
        False,  # Position 11
        False,  # Position 12
        False,  # Position 13
        False,  # Position 14
        True,  # Position 15 (start codon)
        False,  # Position 16
        False,  # Position 17
        True,  # Position 18
        False,  # Position 19
        False,  # Position 20
        True,  # Position 21
        False,  # Position 22
        False,  # Position 23
        True,  # Position 24
        False,  # Position 25
        False,  # Position 26
        True,  # Position 27
        False,  # Position 28
        False,  # Position 29
    ]

    output = map_valid_delta_positions_for_read(read, gene_dict)

    assert len(output) == read.size, "Result length does not match read size."
    assert output == expected_output

    read = Read("gene1", len(gene_dict["gene1"]) - 45, 30)

    expected_output = [
        False,  # Position 0
        True,  # Position 1
        False,  # Position 2
        False,  # Position 3
        True,  # Position 4
        False,  # Position 5
        False,  # Position 6
        True,  # Position 7
        False,  # Position 8
        False,  # Position 9
        True,  # Position 10
        False,  # Position 11
        False,  # Position 12
        True,  # Position 13
        False,  # Position 14
        False,  # Position 15
        True,  # Position 16
        False,  # Position 17
        False,  # Position 18
        True,  # Position 19
        False,  # Position 20
        False,  # Position 21
        True,  # Position 22 (stop codon)
        False,  # Position 23
        False,  # Position 24
        False,  # Position 25
        False,  # Position 26
        False,  # Position 27
        False,  # Position 28
        False,  # Position 29
    ]

    output = map_valid_delta_positions_for_read(read, gene_dict)

    assert len(output) == read.size, "Result length does not match read size."
    assert output == expected_output
