# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtualenv & install deps
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -r pyproject.toml --extra dev
          uv pip install -e .

      - name: Lint with Ruff
        run: |
          source .venv/bin/activate
          ruff check .

      - name: Check formatting with Black
        run: |
          source .venv/bin/activate
          black --check .

      - name: Run tests with Pytest
        run: |
          source .venv/bin/activate
          pytest
